# syntax=docker/dockerfile:1
# check=error=true

FROM ghcr.io/tcely/docker-magic-wormhole-mailbox-server:main AS magic-wormhole-mailbox-server-service

CMD ["--usage-db=/data/usage.sqlite", "--motd=TubeSync"]

